src/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

src/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"
urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
]

src/shop/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(
        max_length=200, verbose_name=_("Category Name"), db_index=True
    )
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse(
            "shop:product_list_by_category", kwargs={"category_slug": self.slug}
        )


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    name = models.CharField(
        max_length=200, db_index=True, verbose_name=_("Product Name")
    )
    slug = models.SlugField(max_length=200, db_index=True, verbose_name=_("Slug"))
    image = models.ImageField(
        upload_to="products/%Y/%m/%d", blank=True, verbose_name=_("Image")
    )
    description = models.TextField(blank=True, verbose_name=_("Description"))
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name=_("Price")
    )
    available = models.BooleanField(default=True, verbose_name=_("Availability"))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Date Created"))
    updated = models.DateTimeField(auto_now=True, verbose_name=_("Date Updated"))

    class Meta:
        ordering = ("name",)
        index_together = (("id", "slug"),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_detail", kwargs={"id": self.id, "slug": self.slug})

src/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.http import HttpResponse
from cart.forms import CartAddProductForm
from .recommender import Recommender


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    print(products)

    template_name = "shop/product/list.html"
    context = {
        "category": category,
        "categories": categories,
        "products": products,
        "categories": categories,
    }

    return render(request, template_name, context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    # adding the add_to_cart form
    cart_product_form = CartAddProductForm()
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)
    template_name = "shop/product/detail.html"
    context = {
        "product": product,
        "cart_product_form": cart_product_form,
        "recommended_products": recommended_products,
    }
    return render(request, template_name, context)

src/shop/templates/shop/product/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>This is the product Dettail page for {{product.name}}</h1>
        <h1>{{product.name}}</h1>
        <p>{{product.description}}</p>

        {% if recommended_products %}
            <div class="recommendations">
                <h3>People who bought this also bought</h3>
                {% for product in recommended_products %}
                    <div class="item">
                        <a href="{{p.get_absolute_url}}">
                            <img src='{% if product.image %}{{product.image.url}}{% else %}{% static "img/no_image.png" %}{% endif %}'>
                        </a>
                        <p><a href="{{product.get_absolute_url }}">{{product.name}}</a></p>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        <form action="{% url "cart:cart_add" product.id %}" method="post">
            {{cart_product_form}}
            {% csrf_token %}
            <input type="submit" value="Add to Cart">
        </form>


</body>

</html>

src/shop/templates/shop/product/list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="cart">
        {% with total_items=cart|length %}
          {% if total_items > 0 %}
            Your Cart:
            <a href="{% url "cart:cart_detail" %}">
                {{total_items}} item{{ total_items|pluralize}}, ${{cart.get_total_price}}
            </a>
            {% else %}
            <p>Your Cart is empty</p>
          {% endif %}
        {% endwith %}
    </div>
    <h1>List of products {% if category %}for {{category}} {% endif %}</h1>
    {% for product in products %}
        <a href="{{product.get_absolute_url}}"><h1>{{product.name}}</h1></a>
    {% endfor %}


    <h1>List of categories</h1>
    <hr>

    {% for category in categories %}
        <a href="{{category.get_absolute_url}}">{{category.name}}</a>
        <br>
    {% endfor %}

    <a href="{% url "cart:cart_detail" %}">Go to shopping Cart</a>
</body>

</html>